name: Python/Flask unittest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Launch mysql server
        run: |
            sudo systemctl start mysql.service
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install boto3
      - name: Test with unittest
        run: |
          python -m unittest discover -s ./test  -p 'test*.py'
